spring:
  application:
    name: fortjoy-admin
  zipkin:
    base-url: http://192.168.50.50:9411
server:
  port: 8887
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {health, info}
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.50.50:10010/eureka/