spring:
  application:
    name: fortjot-gateway
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8887
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10010/eureka
server:
  port: 10080
zuul:
  routes:
    api-a: /api/a/**
    servcieId: feign
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {health, info}