spring:
  application:
    name: fortjoy-eureka
  zipkin:
    base-url: http://192.168.50.50:9411
  boot:
    admin:
      client:
        url: http://192.168.50.50:8887
server:
  port: 10010
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 192.168.50.50
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {health, info}