spring:
  application:
    name: fortjoy-admin
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8887
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: {health, info}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10010/eureka/